### ISSUE TITLE
Display on Github Readme

### ISSUE THREAD

**Issue by louisefindlay23** [zachleat/speedlify-score#1]
Loving Speedlify, @zachleat. I was wondering if there was a way to integrate this into a Github Readme similar to Netlify build status (like the success badge on the main Speedlify repo).

**Comment by zachleat** [comment]
There _is_ a way but it would require a bunch more work to convert the component to render as an image. I’d probably mix the screenshots plugin and point it to a web site that had this on it?

https://www.11ty.dev/docs/services/screenshots/

I think Puppeteer has a selector to image only a subset of a page too.

It’s unlikely that I will do this work though, sorry!
